steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/product-service:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/product-service:$COMMIT_SHA']
options:
  logging: 'NONE'
images:
- 'gcr.io/$PROJECT_ID/product-service:$COMMIT_SHA'
