steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/product-service:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/product-service:latest']
options:
  logging: 'NONE'
images:
- 'gcr.io/$PROJECT_ID/product-service:latest'
